### ISSUE TITLE
Objectif de la formation

### ISSUE THREAD

**Issue by emchateau** [ahn-ens-lyon/formCahier2015#1]
Fil de discussion pour travailler sur les objectifs de la formation
@mingarao

**Comment by emchateau** [comment]
Objectifs de la formation
- initiation à l'utilisation de XQuery
- vue générale du fonctionnement et de l'organisation de SynopsX
- prise en main de SynopsX avec son propre corpus

**Comment by emchateau** [comment]
Objectifs de la formation
- initiation à l'utilisation de XQuery
- vue générale du fonctionnement et de l'organisation de SynopsX
- prise en main de SynopsX avec son propre corpus

**Comment by mingarao** [comment]
Rappel du programme qui nous concerne tel qu'annoncé par CAHIER
A nous de remplir :)

# 1er juillet : Formation à l'outillage XML, XSLT

par Maud Ingarao (ENS Lyon) et Emmanuel Château (Paris Ouest Nanterre) 

## 11h-12h Introduction

## 13h30-15h30 Partie 1/5

## 15h45-17h45 Partie 2/5

# 2 juillet "Initiation à BaseX"

par Maud Ingarao (ENS Lyon) et Emmanuel Château (Paris Ouest Nanterre) 

## 9h30 – 10h45 Introduction

## 11h00 – 12h00 Partie 3 / 5

## 13h30 – 15h30 Partie 4 / 5

## 15h45 – 17h00 Partie 5 / 5

**Comment by mingarao** [comment]
On a en gros un jour et demi à assurer avec une première demi-journée XML/XPATH/XSLT et une journée BaseX

###Intro 1ere demi journée
Je propose un bout d'intro un peu théorique, même si très court, pour rappeler qu'XML est 1 structure arborescente et faire réfléchir 2 secondes là dessus. L'arbre est 1 formalisme parmi d'autres, entraîne un certain type d'expressivité sur les objets, leurs propriétés et leurs relations (par rapport à d'autres formalismes, matrices, graphes...) et un certain type d'algorithmes cf. http://fr.wikipedia.org/wiki/Arbre_%28homonymie%29#En_informatique_et_math.C3.A9matiques
Reprendre les avantages d'XML d'un point de vue informatique (http://editions.ihpc.huma-num.fr/home) et formel (mixed content bien adapté aux données textuelles) et inconvénients informatiques (verbeux, pb de performences) et formels (overlap...)

Puis situer les différentes technos (XML, XPATH, XSL, XQUERY, XFORMS, etc.)

Puis présenter la progression des 2 journées.

**Comment by mingarao** [comment]
On a en gros un jour et demi à assurer avec une première demi-journée XML/XPATH/XSLT et une journée BaseX

### Intro 1ere demi journée (1h)

Je propose un bout d'intro un peu théorique, même si très court, pour rappeler qu'XML est 1 structure arborescente et faire réfléchir 2 secondes là dessus. L'arbre est 1 formalisme parmi d'autres, entraîne un certain type d'expressivité sur les objets, leurs propriétés et leurs relations (par rapport à d'autres formalismes, matrices, graphes...) et un certain type d'algorithmes cf. http://fr.wikipedia.org/wiki/Arbre_%28homonymie%29#En_informatique_et_math.C3.A9matiques
Reprendre les avantages d'XML d'un point de vue informatique (http://editions.ihpc.huma-num.fr/home) et formel (mixed content bien adapté aux données textuelles) et inconvénients informatiques (verbeux, pb de performences) et formels (overlap...)

Puis situer les différentes technos (XML, XPATH, XSL, XQUERY, XFORMS, etc.)

Puis présenter la progression des 2 journées.

**Comment by mingarao** [comment]
Réfléchi très rapidement, à revoir sans doute : 

Puisqu'on a 1 intro + 2 sessions XML/XSLT je propose
intro "théorique" + tour d'horizon d'oXygen
1) xPath, XSLT
2) xQuery

Et 1 intro + 3 sessions sur BaseX
intro : le contexte de création de basex (l'uni Konstanz, etc.)
session 1 : tour d'horizon du logiciel : la base, la GUI, le serveur http, le webdav etc...
session 2 : mettre ses données dans BaseX, utiliser les différentes API pour voir et manipuler ses données
session 3 : constuire une mini webapp (+ démo SynopsX)

En fait ça va passer à toute vitesse cette formation !!!

**Comment by emchateau** [comment]
Salut,
Vu la complexité de XQuery, il me semble que nous aurions plutôt intérêt à centrer l'ensemble de la formation sur SynopsX. C’est à dire présenter XPath et XQuery, BaseX et SynopsX et ne pas aborder XSLT. L’approche XSLT pouvant être strictement réservée à montrer comment associer une transformation avec SynopsX.

**Comment by emchateau** [comment]
Salut, j'ai mis des solides dans le répertoire, as-tu vu ?
J'ai aussi des trucs pour XSLT mais j'ai vraiment peur que cela nous disperse par rapport à Xquery. On en parle demain. D'expérience, le modèle de traitement des transformations est compliqué à expliquer (traitement par défaut, recopie, etc.) et prend surtout du temps à comprendre et à pratiquer,
Amitiés,
Emmanuel
